
import java.io.IOException;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class App {
   
    App() throws IOException {

    }
    private String input() {
        Scanner scanner = new Scanner(System.in);
        String temp_string = scanner.nextLine();
        return temp_string;
    }
    public String getGreeting() {
        return "Hello World!";
    }
    public  void wait_system_load() {
        Scanner scanner = new Scanner(System.in);
        while(!scanner.nextLine().equals("Quit")){} //Quit de tiep tuc
    }
    public static void main(String[] args) throws IOException, InterruptedException{
        App myApp = new App();
        final Manager manager = Manager.getInstance();
        
        myApp.wait_system_load();
        
        Drivers driver_1 = new Drivers("huy", "0123456789", "kontum", Drivers.License.E, 10, manager.getNumOfDrivers());
        Drivers driver_2 = new Drivers("linh", "987654321", "tphcm", Drivers.License.D, 4, manager.getNumOfDrivers());
        Vehicles vehicle_1 = new Vehicles(1, 1, Vehicles.Fuel.diesel, Vehicles.Type.truck, manager.getNumOfVehicles());
        Vehicles vehicle_2 = new Vehicles(2, 2, Vehicles.Fuel.ethanol, Vehicles.Type.coach, manager.getNumOfVehicles());
        
        manager.addVehicle(vehicle_1);
        manager.addVehicle(vehicle_2);
        manager.addUser(new Users("kiet", "kentom", "0946800349", "kennezversion@gmail.com"));
        manager.addUser(new Users("cun", "cun123", "0123456789", "baoanh@gmai.com"));
        manager.addUser(new Users("lebao", "baole321", "0908331349", "baolelb@gamil.com"));
        manager.addUser(new Users("xuanhai", "hai1010", "0917220886", "haixuan@gamil.com"));
        manager.addDriver(driver_1);
        manager.addDriver(driver_2);

        manager.readDriver(manager.getBestDriver(vehicle_1.getType()));
        manager.readVehicle(manager.getBestVehicle(vehicle_1.getType()));
        myApp.wait_system_load();
        
        manager.readAllUsers();
        manager.readAllDrivers();
        manager.readAllVehicles();
        
        manager.removeAllUsers();
        manager.removeAllDrivers();
        manager.removeAllVehicles();
        
        myApp.wait_system_load();
    }
}
