

package menu.driver;
import database.Drivers;
import database.Manager;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;


import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import menu.menu;

/**
 *
 * @author User
 */
public class add extends javax.swing.JFrame {

    /**
     *
     * Creates new form add
     */
     JTable Table;
        DefaultTableModel model = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
        
    };
    public add() throws Exception {
        
        initComponents();
        Enter();
        this.setTitle("ADD DRIVERS");
        
    }
     public void Enter() {
        this.setFocusable(true);
        this.requestFocus();
        Name.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    save();
                }
            }
        });
        KinhNghiem.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    save();
                }
            }
        });
        sdt.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    save();
                }
            }
        });
        address.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    save();
                }
            }
        });
        BangCapjComboBox.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    save();
                }
            }
        });
        HienThi.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    save();
                }
            }
        });
    }
   public boolean checkSo(String str)
   {
       if (str == null || str.length() == 0)
       {
           return false;
       }
       for (char c : str.toCharArray()){
           if(!Character.isDigit(c))
           {
               return false;
           }
       }
       return true;
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Luu = new javax.swing.JButton();
        HienThi = new javax.swing.JButton();
        BangCapjComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        sdt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        KinhNghiem = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(146, 199, 207));
        jPanel1.setForeground(new java.awt.Color(251, 249, 241));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("SVN-Bear", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Back");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 50, -1));

        jLabel1.setFont(new java.awt.Font("SVN-Bear", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Add Drivers");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, 44));

        jLabel3.setFont(new java.awt.Font("SVN-Bear", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Name : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, 30));

        jLabel2.setFont(new java.awt.Font("SVN-Bear", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("License :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 80, 30));

        jLabel4.setFont(new java.awt.Font("SVN-Bear", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Experiences :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 149, 30));

        Name.setBackground(new java.awt.Color(204, 204, 204));
        Name.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 177, 30));

        Luu.setBackground(new java.awt.Color(51, 255, 255));
        Luu.setFont(new java.awt.Font("SVN-Bear", 0, 24)); // NOI18N
        Luu.setForeground(new java.awt.Color(255, 51, 51));
        Luu.setText("Save");
        Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuuActionPerformed(evt);
            }
        });
        jPanel1.add(Luu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 80, 30));

        HienThi.setBackground(new java.awt.Color(255, 102, 102));
        HienThi.setFont(new java.awt.Font("SVN-Bear", 0, 24)); // NOI18N
        HienThi.setForeground(new java.awt.Color(0, 0, 0));
        HienThi.setText("List of Driver");
        HienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HienThiActionPerformed(evt);
            }
        });
        jPanel1.add(HienThi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 190, 40));

        BangCapjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B2", "C", "D", "E" }));
        BangCapjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BangCapjComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(BangCapjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 100, -1));

        jLabel8.setFont(new java.awt.Font("SVN-Bear", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Phone number : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 30));

        sdt.setBackground(new java.awt.Color(204, 204, 204));
        sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdtActionPerformed(evt);
            }
        });
        jPanel1.add(sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 180, 30));

        jLabel9.setFont(new java.awt.Font("SVN-Bear", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Address :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 80, 30));

        address.setBackground(new java.awt.Color(204, 204, 204));
        address.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 180, 30));

        KinhNghiem.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(KinhNghiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 180, 30));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\HocTap\\QuanLiXe\\app\\src\\main\\resources\\icon\\Driver.jpg")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void reset(){
        Name.setText("");
        BangCapjComboBox.setSelectedIndex(0);
        KinhNghiem.setText("");
        address.setText("");
        sdt.setText("");
  }
  
    private void HienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HienThiActionPerformed
        try {
            // TODO add your handling code here:
            new Table().setVisible(true);
            
        } catch (Exception ex) {
            Logger.getLogger(add.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_HienThiActionPerformed

    public  boolean validataForm(){
        if (Name.getText().isEmpty() ||  !checkSo(KinhNghiem.getText())  || !checkSo(sdt.getText()) || address.getText().isEmpty())
        {return false;}
        return true;
    }
    public void showResult(Drivers driver){
       model.addRow(new Object[]{
           driver.getId(),driver.getName(),driver.getLicense().toString(),driver.getExperiences(),driver.getStatus().toString(),driver.getPhonenumber(),driver.getAddress(), driver.getPerformance()
       });
    }
    public void showAll() throws Exception{
    for (Map.Entry<String, Drivers> entry : Manager.getFirebase().driversManager.entrySet())
        {      
           Drivers driver = entry.getValue();
           Manager.readDriver(driver);
           model.addRow(new Object[]{
           driver.getId(),driver.getName(),driver.getLicense().toString(),driver.getExperiences(),driver.getStatus().toString(),driver.getPhonenumber(),driver.getAddress(), driver.getPerformance()
       });      
        }           
    }
    public void save(){
         if(validataForm()){
            try {
                Manager manager = Manager.getInstance();
                String name = Name.getText();
                String phone = sdt.getText();
                String addr = address.getText();
                Drivers.License bangcap = Drivers.fromStringLicense(String.valueOf(BangCapjComboBox.getSelectedItem()));
                int exp =  Integer.parseInt(KinhNghiem.getText());
                int id = Manager.getNewDriverId();
                Drivers driver = new Drivers(name, phone, addr, bangcap, exp, id);
                Manager.addDriver(driver);
                JOptionPane.showMessageDialog(this,"Information saved successfully !");
                reset();
            } catch (IOException ex) {
                Logger.getLogger(add.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        else {
            JOptionPane.showMessageDialog(this,"Please enter the correct and complete fields !");
            reset();
        }
    }
    private void LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuuActionPerformed
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_LuuActionPerformed

    private void BangCapjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BangCapjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BangCapjComboBoxActionPerformed

    private void sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdtActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        menu menuFrame = new menu();
        menuFrame.setVisible(true);
        menuFrame.pack();
        menuFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new add().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(add.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BangCapjComboBox;
    private javax.swing.JButton HienThi;
    private javax.swing.JTextField KinhNghiem;
    private javax.swing.JButton Luu;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField address;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField sdt;
    // End of variables declaration//GEN-END:variables

}
