/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu.driver;

import database.Drivers;
import database.Manager;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import menu.menu;

/**
 *
 * @author User
 */
public class EditDrivers extends javax.swing.JFrame {

    /**
     * Creates new form EditDrivers
     */
    public EditDrivers() {
        initComponents();
        this.setTitle("Edit Drivers");
        Enter();
    }
    public void Enter() {
        this.setFocusable(true);
        this.requestFocus();
        ID.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    save();
                }
            }
        });
        Name.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    save();
                }
            }
        });
        Exper.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    save();
                }
            }
        });
        PhoneNumber.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    save();
                }
            }
        });
        Address.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    save();
                }
            }
        });
        License.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    save();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Address = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Exper = new javax.swing.JTextField();
        License = new javax.swing.JComboBox<>();
        PhoneNumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("SVN-Bear", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Back");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 80, 40));

        jButton1.setFont(new java.awt.Font("SVN-Bear", 1, 18)); // NOI18N
        jButton1.setText("Get  More Data From ID");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 190, -1));

        Address.setBackground(new java.awt.Color(204, 204, 204));
        Address.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 190, -1));

        jLabel8.setFont(new java.awt.Font("SVN-Bear", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Address :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 90, -1));

        jButton3.setFont(new java.awt.Font("SVN-Bear", 1, 18)); // NOI18N
        jButton3.setText("List of Drivers");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, 30));

        Save.setBackground(new java.awt.Color(255, 153, 153));
        Save.setFont(new java.awt.Font("SVN-Bear", 1, 18)); // NOI18N
        Save.setForeground(new java.awt.Color(51, 51, 51));
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel1.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 80, 30));

        jLabel1.setFont(new java.awt.Font("SVN-Bear", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Edit Drivers");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("SVN-Bear", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("SVN-Bear", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Experiences :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("SVN-Bear", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("ID :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("SVN-Bear", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Phone Number :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("SVN-Bear", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("License :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        ID.setBackground(new java.awt.Color(204, 204, 204));
        ID.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 190, -1));

        Name.setBackground(new java.awt.Color(204, 204, 204));
        Name.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 190, -1));

        Exper.setBackground(new java.awt.Color(204, 204, 204));
        Exper.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(Exper, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 190, -1));

        License.setBackground(new java.awt.Color(204, 204, 204));
        License.setForeground(new java.awt.Color(51, 51, 51));
        License.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B2", "C", "D", "E" }));
        License.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LicenseActionPerformed(evt);
            }
        });
        jPanel1.add(License, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        PhoneNumber.setBackground(new java.awt.Color(204, 204, 204));
        PhoneNumber.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(PhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 190, -1));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setIcon(new javax.swing.ImageIcon("E:\\HocTap\\QuanLiXe\\app\\src\\main\\resources\\icon\\editDriver (1).jpg")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Table tableDriver;
        try {
            tableDriver = new Table();
            tableDriver.setVisible(true);
            tableDriver.setLocationRelativeTo(null);
        } catch (Exception ex) {
            Logger.getLogger(EditDrivers.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed
    public boolean checkForm() {
        if (ID.getText().isEmpty() || Name.getText().isEmpty() || Exper.getText().isEmpty() || PhoneNumber.getText().isEmpty() || Address.getText().isEmpty()) {
            return true;
        }
        return false;
    }

    public boolean checkSo(String str) {
        if (str == null || str.length() == 0) {
            return false;
        }
        for (char c : str.toCharArray()) {
            if (!Character.isDigit(c)) {
                return false;
            }
        }
        return true;
    }

    public void reset() {
        Name.setText("");
        PhoneNumber.setText("");
        Address.setText("");
        Exper.setText("");
        License.setSelectedIndex(0);
        ID.setText("");
    }
    public void save(){
        try {
            // TODO add your handling code here:
            if (checkForm()) {
                JOptionPane.showMessageDialog(this, "Enter complete information !");
                reset();
                return;
            } else if (!checkSo(ID.getText()) || !checkSo(Exper.getText())) {
                JOptionPane.showMessageDialog(this, "Please enter the correct format !");
                reset();
                return;
            }
            int id = Integer.parseInt(ID.getText());

            String name = Name.getText();
            String bangcap = String.valueOf(License.getSelectedItem());
            int exper = Integer.parseInt(Exper.getText());
            String phoneNumber = PhoneNumber.getText();
            String address = Address.getText();
            if (!Manager.checkValidDriver(id)) {
                JOptionPane.showMessageDialog(this, "Driver not available !");
                reset();
                return;
            } else if (Manager.checkDriverInTrip(id)) {
                JOptionPane.showMessageDialog(this, "Driver in trip");
                reset();
                return;
            }
            Drivers driver = Manager.getDriver(id);
            driver.setName(name);
            driver.setLicense(bangcap);
            driver.setExperiences(exper);
            driver.setPhonenumber(phoneNumber);
            driver.setAddress(address);
            Manager.updateDrivers();
            JOptionPane.showMessageDialog(this, "Saved successfully !");
            reset();
        } catch (Exception ex) {
            Logger.getLogger(EditDrivers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
       save();
    }//GEN-LAST:event_SaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            if ("".equals(ID.getText()) || !checkSo(ID.getText())) {
                JOptionPane.showMessageDialog(this, "Invalid input");
                return;
            }
            int id = Integer.parseInt(ID.getText());
            if (!Manager.checkValidDriver(id)) {
                JOptionPane.showMessageDialog(this, "Driver not available");
                return;
            }
            Drivers driver = Manager.getDriver(id);
            Name.setText(driver.getName());
            License.setSelectedIndex(Drivers.index_license(driver.getLicense()));
            Exper.setText(String.valueOf(driver.getExperiences()));
            PhoneNumber.setText(driver.getPhonenumber());
            Address.setText(driver.getAddress());
        } catch (Exception ex) {
            Logger.getLogger(EditDrivers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LicenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LicenseActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        menu menuFrame = new menu();
        menuFrame.setVisible(true);
        menuFrame.pack();
        menuFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDrivers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDrivers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDrivers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDrivers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDrivers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Exper;
    private javax.swing.JTextField ID;
    private javax.swing.JComboBox<String> License;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField PhoneNumber;
    private javax.swing.JButton Save;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
